// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { defineConfig } from "prisma/config";

const resolveDatabaseUrl = () => {
  if (process.env.DATABASE_URL) {
    return process.env.DATABASE_URL;
  }

  const envPath = resolve(process.cwd(), ".env");
  if (!existsSync(envPath)) {
    throw new Error("DATABASE_URL is missing and .env file was not found");
  }

  const envFile = readFileSync(envPath, "utf8");
  const match = envFile.match(/^DATABASE_URL=(.*)$/m);

  if (!match?.[1]) {
    throw new Error("DATABASE_URL is missing from .env");
  }

  return match[1].replace(/^"(.*)"$/, "$1");
};

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: resolveDatabaseUrl(),
  },
});
